import type { Metadata } from "next";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Política de privacidad",
  description: "Cómo StoryFlop trata y protege los datos personales de sus usuarios.",
  alternates: { canonical: "/privacidad" },
};

export default function PrivacyPage() {
  return <LegalPage title="Política de privacidad" description="Esta política explica qué información trata StoryFlop, para qué la utiliza y cómo puedes ejercer tus derechos." updatedAt="28 de septiembre de 2026">
    <section><h2>1. Responsable del tratamiento</h2><dl className="legal-details"><div><dt>Responsable</dt><dd>Jaume Bonet Martín</dd></div><div><dt>NIF</dt><dd>47902690S</dd></div><div><dt>Domicilio</dt><dd>Carrer Mas, 114, 08904 L’Hospitalet de Llobregat (Barcelona), España</dd></div><div><dt>Contacto de privacidad</dt><dd><a href="mailto:privacy.storyflop@gmail.com">privacy.storyflop@gmail.com</a></dd></div></dl></section>
    <section><h2>2. Datos que tratamos y cuándo</h2><h3>2.1 Al visitar el sitio</h3><p>El navegador y nuestros proveedores pueden tratar la dirección IP, fecha y hora, página solicitada, referente, navegador, sistema operativo, dispositivo, registros y otros datos técnicos necesarios para entregar el sitio, prevenir ataques y diagnosticar errores.</p><h3>2.2 Al crear o utilizar una sala</h3><ul><li>Identificador técnico de la sesión anónima.</li><li>Nombre o alias y avatar elegidos para participar.</li><li>Nombre y código de la sala, rol y estado de participación.</li><li>Historias de usuario, títulos, descripciones y enlaces introducidos por el equipo.</li><li>Votos, estimaciones, rondas, resultados e historial de cambios.</li></ul><p>Los nombres, avatares, historias y resultados revelados son visibles para quienes acceden a la misma sala. Los votos permanecen ocultos para los demás participantes hasta que se revela la ronda. Quien comparte el enlace o código controla de hecho quién puede solicitar acceso, por lo que no debes publicarlo abiertamente.</p><p>No solicitamos nombre legal, contraseña ni correo electrónico para crear o participar. Te recomendamos utilizar alias y no introducir datos personales o confidenciales en las historias.</p><h3>2.3 Preferencias y publicidad</h3><p>Guardamos la preferencia de idioma y, cuando corresponda, las decisiones de privacidad y publicidad comunicadas mediante la plataforma de consentimiento de Google.</p><h3>2.4 Cuando nos escribes</h3><p>Tratamos la dirección de correo, el contenido del mensaje y los datos que decidas incluir para responder a tu consulta o solicitud.</p></section>
    <section><h2>3. Finalidades y bases jurídicas</h2><div className="legal-table"><div><strong>Prestar el servicio</strong><span>Crear salas, identificar participantes, gestionar historias, votos, resultados y sincronización en tiempo real.</span><span>Ejecución del servicio solicitado (art. 6.1.b RGPD).</span></div><div><strong>Seguridad y prevención de abuso</strong><span>Proteger las salas, limitar usos abusivos, diagnosticar errores y mantener la disponibilidad.</span><span>Interés legítimo (art. 6.1.f RGPD).</span></div><div><strong>Publicidad y medición asociada</strong><span>Mostrar anuncios de Google AdSense en la portada cuando proceda.</span><span>Consentimiento (art. 6.1.a RGPD), solicitado mediante una plataforma de gestión del consentimiento.</span></div><div><strong>Atender consultas y derechos</strong><span>Responder a mensajes enviados a la dirección de privacidad.</span><span>Consentimiento, atención de la solicitud y cumplimiento de obligaciones legales.</span></div></div></section>
    <section><h2>4. Destinatarios y proveedores</h2><p>No vendemos datos personales. Para operar StoryFlop utilizamos proveedores que pueden tratar información por cuenta del responsable o para sus propios fines conforme a sus políticas:</p><ul><li><strong><a href="https://supabase.com/privacy" target="_blank" rel="noreferrer">Supabase</a>:</strong> autenticación anónima, base de datos y comunicación en tiempo real.</li><li><strong><a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noreferrer">Vercel</a>:</strong> alojamiento, distribución y registros técnicos de la aplicación.</li><li><strong><a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Google AdSense y su plataforma de consentimiento</a>:</strong> gestión de preferencias y publicidad en la portada.</li><li><strong>Proveedor de correo:</strong> recepción y gestión de los mensajes enviados a <a href="mailto:privacy.storyflop@gmail.com">privacy.storyflop@gmail.com</a>.</li></ul></section>
    <section><h2>5. Transferencias internacionales</h2><p>Algunos proveedores tienen entidades o infraestructura fuera del Espacio Económico Europeo. Cuando existe una transferencia internacional, se aplican las garantías previstas por el RGPD, como decisiones de adecuación, cláusulas contractuales tipo u otros mecanismos válidos. Puedes consultar información adicional en las políticas de privacidad y acuerdos de tratamiento de cada proveedor.</p></section>
    <section><h2>6. Conservación</h2><ul><li>Las salas que no registran actividad funcional durante 14 días se eliminan automáticamente junto con sus datos vinculados.</li><li>Los usuarios anónimos que quedan sin ninguna sala o membresía se eliminan cuando tienen más de 15 días.</li><li>Las reacciones visuales se transmiten como eventos efímeros y no forman parte del historial persistente de la sala.</li><li>Los registros técnicos de proveedores se conservan durante los plazos definidos por cada proveedor y los necesarios para seguridad o cumplimiento legal.</li><li>Los correos se conservan mientras resulte necesario para responder y, como máximo, durante 24 meses salvo que una obligación legal o una reclamación requieran conservarlos más tiempo.</li></ul></section>
    <section><h2>7. Derechos</h2><p>Puedes ejercer los derechos de acceso (art. 15 RGPD), rectificación (art. 16), supresión (art. 17), limitación (art. 18), portabilidad cuando proceda (art. 20), oposición (art. 21) y retirada del consentimiento con efectos futuros (art. 7.3).</p><p>Escribe a <a href="mailto:privacy.storyflop@gmail.com">privacy.storyflop@gmail.com</a> indicando tu solicitud y la información necesaria para localizar los datos. Responderemos, con carácter general, en el plazo de un mes. Podremos pedir información adicional únicamente cuando sea necesaria para verificar tu identidad.</p><p>También puedes presentar una reclamación ante la <a href="https://www.aepd.es" target="_blank" rel="noreferrer">Agencia Española de Protección de Datos</a>.</p></section>
    <section><h2>8. Seguridad</h2><p>Aplicamos medidas técnicas y organizativas razonables, incluyendo comunicaciones cifradas, control de acceso por sala, políticas de seguridad a nivel de fila y separación de votos privados hasta su revelado. Ningún sistema conectado a Internet puede garantizar seguridad absoluta.</p></section>
    <section><h2>9. Lo que no hacemos</h2><ul><li>No vendemos los datos de las salas ni la información de contacto.</li><li>No utilizamos Google Analytics, Meta Pixel ni LinkedIn Insight Tag.</li><li>No creamos cuentas nominativas ni pedimos contraseñas o correos para participar.</li><li>No compartimos las historias o votos con otras herramientas de planificación salvo que una persona usuaria lo haga mediante un enlace o una futura integración solicitada expresamente.</li><li>No creamos perfiles publicitarios propios. Google y sus proveedores solo podrán utilizar tecnologías publicitarias conforme a la elección recogida por la plataforma de consentimiento.</li></ul></section>
    <section><h2>10. Cambios en esta política</h2><p>Podremos actualizar esta política para reflejar cambios legales, técnicos o funcionales. La fecha de la versión vigente aparecerá al inicio de la página.</p></section>
    <section><h2>11. Contacto</h2><p>Para cualquier pregunta sobre protección de datos, escribe a <a href="mailto:privacy.storyflop@gmail.com">privacy.storyflop@gmail.com</a>.</p></section>
  </LegalPage>;
}
